//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.14-hudson-jaxb-ri-2.1-60--SNAPSHOT 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.06 at 11:57:12 AM PST 
//


package com.oracle.cep.xml.event;

import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, Long>
{


    public Long unmarshal(String value) {
        return (oracle.cep.example.jaxb.customizer.JaxbXmlDateTimeCustomizer.xmlDateTimeToLong(value));
    }

    public String marshal(Long value) {
        return (oracle.cep.example.jaxb.customizer.JaxbXmlDateTimeCustomizer.longToXmlDateTime(value));
    }

}
