//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.14-hudson-jaxb-ri-2.1-60--SNAPSHOT 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.06 at 11:57:12 AM PST 
//


package com.oracle.cep.xml.event;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class Alert
    extends JAXBElement<AlertType>
{

    protected final static QName NAME = new QName("http://xmlns.oracle.com/ns/spatialdemo", "Alert");

    public Alert(AlertType value) {
        super(NAME, ((Class) AlertType.class), null, value);
    }

    public Alert() {
        super(NAME, ((Class) AlertType.class), null, null);
    }

}
