//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.14-hudson-jaxb-ri-2.1-60--SNAPSHOT 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.06 at 11:57:12 AM PST 
//


package com.oracle.cep.xml.event;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for AlertType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlertType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShipPos" type="{http://xmlns.oracle.com/ns/spatialdemo}ShipPosType"/>
 *         &lt;element name="AlertMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AlertSeverity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AlertDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlertType", propOrder = {
    "shipPos",
    "alertMessage",
    "alertSeverity",
    "alertDateTime"
})
public class AlertType
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "ShipPos", required = true)
    protected ShipPosType shipPos;
    @XmlElement(name = "AlertMessage", required = true)
    protected String alertMessage;
    @XmlElement(name = "AlertSeverity")
    protected int alertSeverity;
    @XmlElement(name = "AlertDateTime", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Long alertDateTime;

    /**
     * Gets the value of the shipPos property.
     * 
     * @return
     *     possible object is
     *     {@link ShipPosType }
     *     
     */
    public ShipPosType getShipPos() {
        return shipPos;
    }

    /**
     * Sets the value of the shipPos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipPosType }
     *     
     */
    public void setShipPos(ShipPosType value) {
        this.shipPos = value;
    }

    /**
     * Gets the value of the alertMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertMessage() {
        return alertMessage;
    }

    /**
     * Sets the value of the alertMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertMessage(String value) {
        this.alertMessage = value;
    }

    /**
     * Gets the value of the alertSeverity property.
     * 
     */
    public int getAlertSeverity() {
        return alertSeverity;
    }

    /**
     * Sets the value of the alertSeverity property.
     * 
     */
    public void setAlertSeverity(int value) {
        this.alertSeverity = value;
    }

    /**
     * Gets the value of the alertDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Long getAlertDateTime() {
        return alertDateTime;
    }

    /**
     * Sets the value of the alertDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertDateTime(Long value) {
        this.alertDateTime = value;
    }

}
