//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.14-hudson-jaxb-ri-2.1-60--SNAPSHOT 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.06 at 11:57:12 AM PST 
//


package com.oracle.cep.xml.event;

import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.oracle.cep.xml.event package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.oracle.cep.xml.event
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShipPosType }
     * 
     */
    public ShipPosType createShipPosType() {
        return new ShipPosType();
    }

    /**
     * Create an instance of {@link AlertType }
     * 
     */
    public AlertType createAlertType() {
        return new AlertType();
    }

    /**
     * Create an instance of {@link ShipPositions }
     * 
     */
    public ShipPositions createShipPositions() {
        return new ShipPositions();
    }

    /**
     * Create an instance of {@link ShipPosList }}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/ns/spatialdemo", name = "ShipPosList")
    public ShipPosList createShipPosList(ShipPositions value) {
        return new ShipPosList(value);
    }

    /**
     * Create an instance of {@link Alert }}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/ns/spatialdemo", name = "Alert")
    public Alert createAlert(AlertType value) {
        return new Alert(value);
    }

    /**
     * Create an instance of {@link ShipPos }}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/ns/spatialdemo", name = "ShipPos")
    public ShipPos createShipPos(ShipPosType value) {
        return new ShipPos(value);
    }

}
